apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-api-db: "true"
  name: cp-api-db
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    cloud-pipeline/cp-api-db: "true"
