apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-git: "true"
  name: cp-git
  namespace: default
spec:
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 30080
    targetPort: 30080
    name: cp-git-port-http
  - protocol: TCP
    port: 22
    targetPort: 22
    name: cp-git-port-ssh
  type: NodePort
  selector:
    cloud-pipeline/cp-git: "true"
