apiVersion: v1
kind: Pod
metadata:
  name: cp-idp
  namespace: default
  labels:
    cloud-pipeline/cp-idp: "true"
spec:
  nodeSelector:
    cloud-pipeline/cp-idp: "true"
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
    - name: cp-idp
      image: lifescience/cloud-pipeline:idp-$CP_VERSION
      imagePullPolicy: "IfNotPresent"
      command: ["/init"]
      ports:
        - containerPort: 8080
      envFrom:
      - configMapRef:
          name: cp-config-global
      volumeMounts:
        - mountPath: /opt/idp/pki
          name: idp-pki
        - mountPath: /opt/api/pki
          name: api-pki
        - mountPath: /opt/gitlab/pki
          name: git-pki
      readinessProbe:
        httpGet:
          path: /metadata
          port: 8080
          scheme: HTTPS
        initialDelaySeconds: 5
        periodSeconds: 10
  volumes:
    - name: idp-pki
      hostPath:
        path: /opt/idp/pki
    - name: api-pki
      hostPath:
        path: /opt/api/pki
    - name: git-pki
      hostPath:
        path: /opt/gitlab/pki
  imagePullSecrets:
    - name: cp-distr-docker-registry-secret
  