apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-edge: "true"
    cloud-pipeline/role: "EDGE"
  name: cp-edge
  namespace: default
spec:
  ports:
  - protocol: TCP
    nodePort: 31081
    port: 31081
    targetPort: 8080
    name: cp-edge-port-https
  - protocol: TCP
    nodePort: 31091
    port: 31091
    targetPort: 8081
    name: cp-edge-port-connect
  type: NodePort
  selector:
    cloud-pipeline/cp-edge: "true"
