apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-docker-comp: "true"
  name: cp-docker-comp
  namespace: default
spec:
  ports:
  - protocol: TCP
    nodePort: 31082
    port: 31082
    targetPort: 8080
    name: cp-docker-comp-port-http
  type: NodePort
  selector:
    cloud-pipeline/cp-docker-comp: "true"
