apiVersion: v1
kind: Service
metadata:
  name: cp-test
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: test
  selector:
    cloud-pipeline/cp-test: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: cp-test
  namespace: default
  labels:
    cloud-pipeline/cp-test: "true"
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
    - name: cp-test
      image: library/centos:7
      imagePullPolicy: "IfNotPresent"
      command: ["bash","-c"]
      args: ["sleep infinity"]
      volumeMounts:
      - name: cp-cluster-ssh-key
        mountPath: "/etc/cp_ssh"
        readOnly: true
  volumes:
  - name: cp-cluster-ssh-key
    secret:
      secretName: cp-cluster-ssh-key
      defaultMode: 384